name: React Vite CI/CD

on:  # Define event triggers here
  push:  # Trigger workflow on push to the main branch
    branches:
      - main
  pull_request:  # Trigger workflow on pull requests to the main branch
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build
